apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: mysite
build:
  artifacts:
  - image: kilhyun/mysite-web
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  helm:
    releases:
    - name: mysite
      chartPath: deployments/mysite
  kubeContext: docker-desktop
