apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - name: db
        image: postgres
        imagePullPolicy: ""
        resources: {}
{{- if .Values.db.env }}
        env:
{{- range $key, $val := .Values.db.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
{{- end}}
{{- end}}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
