apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - python
        - manage.py
        - runserver
        - 0.0.0.0:8000
{{- if .Values.web.env }}
        env:
{{- range $key, $val := .Values.web.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
{{- end}}
{{- end}}
        image: kilhyun/mysite-web:6e35eaf-dirty
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 8000
        resources: {}
        # volumeMounts:
        # - mountPath: /code
        #   name: web-claim0
      restartPolicy: Always
      serviceAccountName: ""
      # volumes:
      # - name: web-claim0
      #   persistentVolumeClaim:
      #     claimName: web-claim0
status: {}
